name: Lint and Test

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Python Version Cache
        run: ls /opt/hostedtoolcache/Python || echo "Python versions not found"

      - name: Show Environment Variables
        run: env

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          check-latest: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Python Version
        run: python --version

      - name: Install Dependencies
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install black flake8

      - name: Run Black Formatter Check
        run: |
          . .venv/bin/activate
          black --check src || exit 1

      - name: Run Flake8 Linter
        run: |
          . .venv/bin/activate
          flake8 src || exit 1

      - name: Output Success Message
        if: success()
        run: echo "Linting and formatting checks passed successfully!"
