name: Lint and Format

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clear Python Cache
        run: |
          sudo rm -rf ~/.cache/pip
          sudo rm -rf ~/.pyenv
          sudo rm -rf .venv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          check-latest: true

      - name: Verify Python Version
        run: python --version

      - name: Install Dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install black flake8

      - name: Run Black for Formatting Check
        run: |
          . .venv/bin/activate
          if [ -d "tests" ]; then
            black --check src tests
          else
            black --check src
          fi

      - name: Run Flake8 for Linting
        run: |
          . .venv/bin/activate
          if [ -d "tests" ]; then
            flake8 src tests
          else
            flake8 src
          fi
