name: Test Application

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make ctl.sh Executable
        run: chmod +x ./ctl.sh

      - name: Run Tests with ctl.sh
        run: ./ctl.sh test dev
